"""Deterministic context-packaging primitives."""

from .cove_adapter import (
    COVE_SEMANTIC,
    PEMS_SEMANTIC,
    SERIALIZER,
    SUPPORTED_TUPLES,
    CoveAdapterError,
    CoveSemanticTuple,
    decode_cove_pems,
    encode_cove_pems,
)
from .pack_builder import (
    PACK_BUILDER_CONTRACT,
    PACK_BUILDER_CONTRACT_V1,
    PACK_BUILDER_CONTRACT_V2,
    PACK_CONTRACT,
    PACK_CONTRACT_V1,
    PACK_CONTRACT_V2,
    ContextPackBuildResult,
    build_context_pack,
)
from .pems_projection import (
    PemsProjectionResult,
    ProjectedKnowledge,
    ProjectionCause,
    project_pems,
)
from .persistence_adapter import (
    IMMUTABLE_OUTPUT_COLLISION,
    NO_CHANGE,
    PERSISTED,
    ImmutableOutputCollisionError,
    PersistenceBoundaryError,
    PersistenceResult,
    persist_immutable_artifact,
)
from .provenance_bridge import (
    PROVENANCE_BRIDGE_INVALID,
    PROVENANCE_REGISTRY_CONTRACT,
    PROVENANCE_SOURCE_COLLISION,
    ProvenanceRegistryResult,
    derive_context_source_id,
    derive_provenance_registry,
    persist_provenance_registry,
)
from .renderer import (
    FRAMING_CONTRACT,
    RENDERED_ACTIVATION_CONTRACT,
    RENDERER_CONTRACT,
    RENDERER_PROFILE_CONTRACT,
    RenderedActivationDecodeResult,
    RenderedActivationResult,
    decode_rendered_activation,
    render_context_pack,
)
from .source_resolver import (
    AdapterResult,
    ResolvedSource,
    SourceResolutionResult,
    resolve_sources,
)

__all__ = [
    "AdapterResult",
    "COVE_SEMANTIC",
    "ContextPackBuildResult",
    "CoveAdapterError",
    "CoveSemanticTuple",
    "FRAMING_CONTRACT",
    "IMMUTABLE_OUTPUT_COLLISION",
    "ImmutableOutputCollisionError",
    "NO_CHANGE",
    "PACK_BUILDER_CONTRACT",
    "PACK_BUILDER_CONTRACT_V1",
    "PACK_BUILDER_CONTRACT_V2",
    "PACK_CONTRACT",
    "PACK_CONTRACT_V1",
    "PACK_CONTRACT_V2",
    "PEMS_SEMANTIC",
    "PERSISTED",
    "PROVENANCE_BRIDGE_INVALID",
    "PROVENANCE_REGISTRY_CONTRACT",
    "PROVENANCE_SOURCE_COLLISION",
    "PersistenceBoundaryError",
    "PersistenceResult",
    "PemsProjectionResult",
    "ProjectedKnowledge",
    "ProjectionCause",
    "ProvenanceRegistryResult",
    "RENDERED_ACTIVATION_CONTRACT",
    "RENDERER_CONTRACT",
    "RENDERER_PROFILE_CONTRACT",
    "RenderedActivationDecodeResult",
    "RenderedActivationResult",
    "ResolvedSource",
    "SERIALIZER",
    "SUPPORTED_TUPLES",
    "SourceResolutionResult",
    "build_context_pack",
    "decode_cove_pems",
    "decode_rendered_activation",
    "derive_context_source_id",
    "derive_provenance_registry",
    "encode_cove_pems",
    "persist_immutable_artifact",
    "persist_provenance_registry",
    "project_pems",
    "render_context_pack",
    "resolve_sources",
]
